# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'gd'

    # Use warmup messages
    messenger: true

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public/'
                cache_prefix: 'images/cache'

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public/images'

    filter_sets:
        small:
            cache: default
            quality: 75
            filters:
                downscale:
                    max: [480, 480]

        medium:
            cache: default
            quality: 75
            filters:
                downscale:
                    max: [980, 980]

        large:
            cache: default
            quality: 75
            filters:
                downscale:
                    max: [1690, 1690]
