framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            sync: 'sync://'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: async
                        type: fanout
                    queues:
                        async: ~

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'

        routing:
            'App\Message\DailyOccurrenceMessage': async
            'App\Message\EventMessage': async
            'App\Message\FeedItemDataMessage': async
            'App\Message\FeedItemNormalizationMessage': async
            'App\Message\GeocoderMessage': async
            'App\Message\ImageMessage': async
            'App\Message\IndexMessage': async
            'App\Message\ReadFeedMessage': async
            'Liip\ImagineBundle\Message\WarmupCache': async
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'in-memory://'
