services:
  phpfpm:
    depends_on:
      - rabbit

  nginx:
    environment:
      APP_PATH_PREFIX: ${APP_PATH_PREFIX}
    labels:
      # Scope hosting by path prefix to allow shared hosting with legacy EventDB
      # 'https://api.detskeriaarhus.dk/easyadmin/' -> Legacy EventDB
      # 'https://api.detskeriaarhus.dk/media/' -> Legacy EventDB
      # 'https://api.detskeriaarhus.dk/admin/' -> EventDB v2
      # 'https://api.detskeriaarhus.dk/images/' -> EventDB v2
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`) && (PathPrefix(`${APP_PATH_PREFIX}`) || PathPrefix(`/images`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`) && (PathPrefix(`${APP_PATH_PREFIX}`) || PathPrefix(`/images`))"

  rabbit:
    image: rabbitmq:3.12-management-alpine
    restart: unless-stopped
    networks:
      - app
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - "./.docker/data/rabbit:/var/lib/rabbitmq/mnesia"

  supervisor:
    # @TODO: Create supervisor with ansible, when merged with Ture's PR
    image: itkdev/supervisor-php8.3:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async
      - APP_SUPERVISOR_WORKERS=4
      - APP_SUPERVISOR_USER=deploy
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - rabbit
