version: "3"

services:
  phpfpm:
    depends_on:
      - elasticsearch
      - rabbit

  rabbit:
    image: rabbitmq:3.12-management-alpine
    networks:
      - app
      - frontend
    ports:
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'

  elasticsearch:
    image: elasticsearch:8.10.2
    networks:
      - app
      - frontend
    ports:
      - "9200"
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M
    volumes:
      - ./.docker/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  node:
    image: node:18
    networks:
      - app
    working_dir: /app
    volumes:
      - .:/app
