services:
  phpfpm:
    image: itkdev/php8.4-fpm:latest
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=40M
      - PHP_POST_MAX_SIZE=50M
    depends_on:
      - elasticsearch
      - rabbit

  nginx:
    environment:
      APP_PATH_PREFIX: ${APP_PATH_PREFIX}
      NGINX_MAX_BODY_SIZE: 50M

  rabbit:
    image: rabbitmq:4-management-alpine
    networks:
      - app
      - frontend
    ports:
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'

  elasticsearch:
    image: elasticsearch:8.13.0
    networks:
      - app
      - frontend
    ports:
      - "9200"
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M
    volumes:
      - ./.docker/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  node:
    image: node:22
    networks:
      - app
    working_dir: /app
    volumes:
      - .:/app
