services:
  phpfpm:
    environment:
      - PHP_MEMORY_LIMIT=256M
    depends_on:
      - rabbit
    volumes:
      - ../../shared/.env.local:/app/.env.local
      - ../../shared/images:/app/public/images/

  nginx:
    environment:
      APP_PATH_PREFIX: ${APP_PATH_PREFIX}
    volumes:
      - ../../shared/images:/app/public/images/

  supervisor:
    # @TODO: Create supervisor with ansible, when merged with Ture's PR
    image: itkdev/supervisor-php8.3:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async scheduler_default
      - APP_SUPERVISOR_WORKERS=4
      - APP_SUPERVISOR_USER=deploy
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - PHP_TIMEZONE=UTC
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3.13-management-alpine
    restart: unless-stopped
    networks:
      - app
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - "./.docker/data/rabbit:/var/lib/rabbitmq/mnesia"
