version: "3"

services:
  rabbit:
    image: rabbitmq:3.12-management-alpine
    restart: unless-stopped
    networks:
      - app
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - "./.docker/data/rabbit:/var/lib/rabbitmq/mnesia"

  supervisor:
    image: itkdev/supervisor-php8.1:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async
      - APP_SUPERVISOR_WORKERS=4
      - APP_SUPERVISOR_USER=deploy
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
