services:
  phpfpm:
    depends_on:
      - elasticsearch
      - rabbit

  nginx:
    environment:
      APP_PATH_PREFIX: ${APP_PATH_PREFIX}
    labels:
      # Scope hosting by path prefix to allow shared hosting with legacy EventDB
      # 'https://api.detskeriaarhus.dk/easyadmin/' -> Legacy EventDB
      # 'https://api.detskeriaarhus.dk/admin/' -> EventDB v2
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_DOMAIN}`) && (PathPrefix(`${APP_PATH_PREFIX}`) || PathPrefix(`/images`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`) && (PathPrefix(`${APP_PATH_PREFIX}`) || PathPrefix(`/images`))"
      # HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  rabbit:
    image: rabbitmq:3.12-management-alpine
    networks:
      - app
      - frontend
    ports:
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'

  elasticsearch:
    image: elasticsearch:8.13.0
    networks:
      - app
      - frontend
    ports:
      - "9200"
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M
    volumes:
      - ./.docker/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  node:
    image: node:18
    networks:
      - app
    working_dir: /app
    volumes:
      - .:/app
