<?php

declare(strict_types=1);

namespace App\Tests\Functional;

use App\Entity\User;
use App\Repository\UserRepository;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

abstract class AbstractAdminTestCase extends WebTestCase
{
    protected KernelBrowser $client;
    protected AbstractDatabaseTool $databaseTool;

    protected function setUp(): void
    {
        parent::setUp();

        $this->client = static::createClient();
        $this->databaseTool = static::getContainer()
            ->get(DatabaseToolCollection::class)
            ->get();
    }

    /**
     * @param list<class-string> $classes
     */
    protected function loadFixtures(array $classes): void
    {
        $this->databaseTool->loadFixtures($classes);
    }

    protected function loginAs(string $email): KernelBrowser
    {
        $this->client->loginUser($this->findUser($email));

        return $this->client;
    }

    protected function findUser(string $email): User
    {
        $user = static::getContainer()->get(UserRepository::class)->findOneBy(['mail' => $email]);

        if (null === $user) {
            throw new \RuntimeException(sprintf('User "%s" not found. Did you load TestUserFixtures?', $email));
        }

        return $user;
    }

    /**
     * Build an EasyAdmin URL via the pretty URL routes generated by the
     * EasyAdmin route loader.
     *
     * EasyAdmin registers routes named `admin_<snake_name>_<action>` for each
     * CRUD controller and redirects query-string URLs to these pretty URLs.
     * Generating the pretty URL directly avoids the 302 round-trip in tests.
     *
     * We avoid the AdminUrlGenerator service because it depends on the current
     * request context which is not available before the test client issues a request.
     *
     * @param class-string               $crudControllerFqcn
     * @param array<string, scalar|null> $extra
     */
    protected function adminUrl(string $crudControllerFqcn, string $action = Action::INDEX, array $extra = []): string
    {
        $routeName = sprintf('admin_%s_%s', $this->routeSlugFor($crudControllerFqcn), $action);

        $params = [];
        if (isset($extra['entityId'])) {
            $params['entityId'] = $extra['entityId'];
            unset($extra['entityId']);
        }

        $url = static::getContainer()->get('router')->generate($routeName, $params);

        // Append any remaining query parameters (filters, referrer, etc.).
        $filtered = array_filter(
            $extra,
            static fn (bool|float|int|string|null $value): bool => null !== $value,
        );
        if ([] !== $filtered) {
            $separator = str_contains($url, '?') ? '&' : '?';
            $url .= $separator.http_build_query($filtered);
        }

        return $url;
    }

    /**
     * Derive the snake_case slug EasyAdmin uses in its route names from the
     * CRUD controller class name, e.g. `MyEventCrudController` -> `my_event`.
     *
     * @param class-string $crudControllerFqcn
     */
    private function routeSlugFor(string $crudControllerFqcn): string
    {
        $shortName = substr((string) strrchr($crudControllerFqcn, '\\'), 1);
        $shortName = preg_replace('/(CrudController|Controller)$/', '', $shortName) ?? $shortName;

        $snake = preg_replace('/(?<!^)([A-Z])/', '_$1', $shortName) ?? $shortName;

        return strtolower($snake);
    }
}
